version: '3.7'

services:
  go:
    build:
      context: .
    ports: 
      - 8080:8080
    volumes:
      - .:/go

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    volumes:
    - ./database:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080