version: '3.7'

services:
  go:
    build:
      context: .
    ports: 
      - 8080:8080
    volumes:
      - .:/go

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: mydb
    volumes:
    - ./database:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "DBZHYBLZbdSzACgThrHAHCnqUb4wx2xg"
      REDIS_DB: "furycache"
    volumes:
      - redis-data:/data

volumes:
  redis-data: