version: '3.7'

services:
  go:
    build:
      context: .
    ports: 
      - 8080:8080
    volumes:
      - .:/go
    depends_on:
     - redis
    networks:
      - internal

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "DBZHYBLZbdSzACgThrHAHCnqUb4wx2xg"
      REDIS_DB: "furycache"
    volumes:
      - redis-data:/data
    networks:
    - internal

volumes:
  redis-data:

networks:
  internal: